service: augmented-spotify-api

provider:
  name: aws
  runtime: ruby2.5
  region: ${env:AWS_REGION}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
       - dynamodb:Query
       - dynamodb:Scan
       - dynamodb:GetItem
       - dynamodb:PutItem
       - dynamodb:UpdateItem
       - dynamodb:DeleteItem
      Resource: ${env:DYNAMODB_METADATA_ARN}

functions:
  api:
    handler: rack_adapter.handler
    events:
      - http:
          path: artists/{id}
          method: get
          integration: lambda-proxy
      - http:
          path: artists/{id}/metadata
          method: post
          integration: lambda-proxy

plugins:
  - serverless-rack
  - serverless-dotenv-plugin

package:
  exclude:
    - .env
    - .env.*
    - README.md
    - openapi.yml
    - spec/**
    