service: augmented-spotify-api

provider:
  name: aws
  runtime: ruby2.5
  region: ${env:AWS_REGION}

functions:
  api:
    handler: rack_adapter.handler
    events:
      - http:
          path: artists/{id}
          method: get
          integration: lambda-proxy
      - http:
          path: artists/{id}/metadata
          method: post
          integration: lambda-proxy

plugins:
  - serverless-rack
  - serverless-dotenv-plugin

package:
  exclude:
    - .env
    - .env.*
    - README.md
    - openapi.yml
    - spec/**
    