service: augmented-spotify-api

provider:
  name: aws
  runtime: ruby2.5
  region: ${env:AWS_REGION}

functions:
  api:
    handler: rack_adapter.handler
    events:
      - http: ANY /
      - http: ANY {proxy+}

plugins:
  - serverless-rack
  - serverless-dotenv-plugin
