service: augmented-spotify-api

provider:
  name: aws
  runtime: ruby2.5

functions:
  hello:
    handler: handler.hello

plugins:
  - serverless-hooks-plugin

custom:
  hooks:
    package:initialize:
      - bundle install --deployment
    package:finalize:
      - rm -rf .bundle